export const CHANGE_USER_DATA_FETCHING = "CHANGE_USER_DATA_FETCHING";
export const CHANGE_USER_DATA_SUCCESS = "CHANGE_USER_DATA_SUCCESS";
export const CHANGE_USER_DATA_ERROR = "CHANGE_USER_DATA_ERROR";

export const REGISTER_NEW_USER_FETCHING = "REGISTER_NEW_USER_FETCHING";
export const REGISTER_NEW_USER_SUCCESS = "REGISTER_NEW_USER_SUCCESS";
export const REGISTER_NEW_USER_ERROR = "REGISTER_NEW_USER_ERROR";

export const SIGN_IN_FETCHING = "SIGN_IN_FETCHING";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";

export const SIGN_OUT_FETCHING = "SIGN_OUT_FETCHING";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";

export const ADD_GUEST_APPOINTMENT_FETCHING = "ADD_GUEST_APPOINTMENT_FETCHING";
export const ADD_GUEST_APPOINTMENT_SUCCESS = "ADD_GUEST_APPOINTMENT_SUCCESS";
export const ADD_GUEST_APPOINTMENT_ERROR = "ADD_GUEST_APPOINTMENT_ERROR";

export const ADD_USER_APPOINTMENT_FETCHING = "ADD_USER_APPOINTMENT_FETCHING";
export const ADD_USER_APPOINTMENT_SUCCESS = "ADD_USER_APPOINTMENT_SUCCESS";
export const ADD_USER_APPOINTMENT_ERROR = "ADD_USER_APPOINTMENT_ERROR";

export const DELETE_USER_APPOINTMENT_FETCHING = "DELETE_USER_APPOINTMENT_FETCHING";
export const DELETE_USER_APPOINTMENT_SUCCESS = "DELETE_USER_APPOINTMENT_SUCCESS";
export const DELETE_USER_APPOINTMENT_ERROR = "DELETE_USER_APPOINTMENT_ERROR";

export const POPUP_CLOSE = "POPUP_CLOSE";

